port: ":8080"

db:
  host: "localhost"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

salt: "jjKJwADA21jdas012d"

token:
  key: "fwijwa3IJ$oof90fsavsfSADqiwe"
  TTL: "12 * time.Hour"
